version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: test-nodejs
    ports:
      - "3006:3006"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongodb
